import { authRouter } from "./auth-routes.js";
import { accountingRouter } from "./accounting-routes.js";
import { clientRouter } from "./client-routes.js";
import { companyContextRouter } from "./company-context-routes.js";
import { companyRouter } from "./company-routes.js";
import { companyPaymentRouter } from "./company-payment-routes.js";
import { dashboardRouter } from "./dashboard-routes.js";
import { financeSessionRouter } from "./finance-session-routes.js";
import { integrationRouter } from "./integration-routes.js";
import { loanRouter } from "./loans/index.js";
import { notificationRouter } from "./notification-routes.js";
import { opsRouter } from "./ops-routes.js";
import { regulatoryReportRouter } from "./regulatory-report-routes.js";
import { userRouter } from "./user-routes.js";
import { adminSupportRouter } from "./admin-support-routes.js";
import { adminMonitoringRouter } from "./admin-monitoring-routes.js";
import { adminNotificationsRouter } from "./admin-notifications-routes.js";
import { adminAuditRouter } from "./admin-audit-routes.js";
import { adminSettingsRouter } from "./admin-settings-routes.js";
import { seedRouter } from "./seed-routes.js";
import { emailRouter } from "./email-routes.js";
import { carteiraRouter } from "./carteira-routes.js";
import { riskRouter } from "./risk-routes.js";
import { eventosRouter } from "./eventos-routes.js";
import { paymentMethodRouter } from "./payment-method-routes.js";
import { creditProductRouter } from "./credit-product-routes.js";
import { financialCalendarRouter } from "./financial-calendar-routes.js";
import { globalSearchRouter } from "./global-search-routes.js";
import { processLogRouter } from "./process-log-routes.js";
import { portalRouter } from "./portal-routes.js";

export function registerApiRoutes(app) {
  app.use("/api/auth", authRouter);
  app.use("/api/accounting", accountingRouter);
  app.use("/api/clients", clientRouter);
  app.use("/api/loans", loanRouter);
  app.use("/api/dashboard", dashboardRouter);
  app.use("/api/finance-session", financeSessionRouter);
  app.use("/api/integrations", integrationRouter);
  app.use("/api/notifications", notificationRouter);
  app.use("/api/ops", opsRouter);
  app.use("/api/reports", regulatoryReportRouter);
  app.use("/api/users", userRouter);
  app.use("/api/admin/companies", companyRouter);
  app.use("/api/admin/payments", companyPaymentRouter);
  app.use("/api/admin/support", adminSupportRouter);
  app.use("/api/admin/monitoring", adminMonitoringRouter);
  app.use("/api/admin/notifications", adminNotificationsRouter);
  app.use("/api/admin/audit", adminAuditRouter);
  app.use("/api/admin/settings", adminSettingsRouter);
  app.use("/api/company", companyContextRouter);
  app.use("/api/email", emailRouter);
  app.use("/api/carteiras", carteiraRouter);
  app.use("/api/payment-methods", paymentMethodRouter);
  app.use("/api/risk", riskRouter);
  app.use("/api/eventos", eventosRouter);
  app.use("/api/process-log", processLogRouter);
  app.use("/api/portal", portalRouter);
  app.use("/api/search", globalSearchRouter);
  app.use("/api/seed", seedRouter);
  app.use("/api/credit-products", creditProductRouter);
  app.use("/api/financial-calendar", financialCalendarRouter);
}
